const { Proker } = require("../Model");

const proker_dummy = [
  {
    nama_program: "Excellence Supply Management",
    plan: "Monitoring cheklist dan konsistensi New infracnr dan new OSASE periode Bulan  Sept. 2021",
    target: "continue",
    bulan: "september",
    keterangan: "progres",
    status: "progres",
    divisi_id: 1,
  },
  {
    nama_program: "Always On Services",
    plan: "Maintenance Rutine Perangkat Energy ( DEG, Rect, Batt, AC, Ints Daya, Grounding, UPS )Bln Sept. 2021",
    target: "continue",
    bulan: "september",
    keterangan: "progres",
    status: "progres",
    divisi_id: 1,
  },
  {
    nama_program: "Total Solution for Customer",
    plan: "Pemasangan catuan power AC dan DC untuk mitra Colocation all Sto Network Area & IS Operation",
    target: "continue",
    bulan: "september",
    keterangan: "progres",
    status: "progres",
    divisi_id: 1,
  },
  {
    nama_program: "Always On Services",
    plan: "Service AC ruang perangkat periode Bulan Sept. 2021 di STO .GBR,KMY & HRB PLAZA INDONESIA",
    target: "continue",
    bulan: "september",
    keterangan: "progres",
    status: "progres",
    divisi_id: 1,
  },

  {
    nama_program: "Always On Services",
    plan: "Perbaikan AC perangkat periode Bulan Sept. 2021 di STO GBR, CKN, CPP, CID.KMY & HRB",
    target: "continue",
    bulan: "september",
    keterangan: "progres",
    status: "progres",
    divisi_id: 1,
  },

  {
    nama_program: "Always On Services",
    plan: "Maintenance /Pemanasan Genset Caterpillar kap.1350 Kva Sto Cempaka Putih",
    target: "M I Sept. 2021",
    bulan: "september",
    keterangan: "close",
    status: "close",
    divisi_id: 1,
  },

  {
    nama_program: "Always On Services",
    plan: "Maintenance Rectifier Peco,Argus ,Sharf,Fujitzu dan BIR Rectifier /Ruangannya di Sto Cempaka Putih",
    target: "M I Sept. 2021",
    bulan: "september",
    keterangan: "close",
    status: "close",
    divisi_id: 1,
  },

  {
    nama_program: "Always On Services",
    plan: "Penambahan Air Aquades Batere BAE Sebanyak 4 bank di Sto Cempaka Putih",
    target: "    target: ",
    bulan: "september",
    keterangan: "close",
    status: "close",
    divisi_id: 1,
  },

  {
    nama_program: "Always On Services",
    plan: "Maintenance Trafo Kap.800 Kva dan BIR Ruangannya di Sto Cempaka putih",
    target: "M II Sept. 2021",
    bulan: "september",
    keterangan: "close",
    status: "close",
    divisi_id: 1,
  },
  {
    nama_program: "Always On Services",
    plan: "Maintenance /Pemanasan Genset Caterpillar kap.1360 Kva Sto Cikini    ",
    target: "M II Sept. 2021",
    bulan: "september",
    keterangan: "close",
    status: "close",
    divisi_id: 1,
  },
  {
    nama_program: "Always On Services",
    plan: "Maintenance  Battery  Sentral AT&T, EWSD,Transmisi dan BIR Battery & Ruangannya di Sto Cikini",
    target: "M II Sept. 2021",
    bulan: "september",
    keterangan: "close",
    status: "close",
    divisi_id: 1,
  },
  {
    nama_program: "Always On Services",
    plan: "Maintenance Rectifier Peco,Argus ,Siemen,Emerson,Fujitzu dan BIR Rectifier /Ruangannya di Sto Cikini",
    target: "M II Sept. 2021",
    bulan: "september",
    keterangan: "close",
    status: "close",
    divisi_id: 1,
  },
  {
    nama_program: "Always On Services",
    plan: "Penambahan Air Aquades Batere BAE Kap.2500 AH sebanyak 3 bank di Sto Cikini    ",
    target: "M III Sept. 2021",
    bulan: "september",
    keterangan: "close",
    status: "close",
    divisi_id: 1,
  },
  {
    nama_program: "Always On Services",
    plan: "Maintenance Trafo Kap.1250 Kva dan BIR Ruangannya di Sto Cikini ",
    target: "M III Sept. 2021",
    bulan: "september",
    keterangan: "close",
    status: "close",
    divisi_id: 1,
  },

  {
    nama_program: "Always On Services",
    plan: "Maintenance /Pemanasan Genset Caterpillar kap.2 X 2500 Kva Sto Gambir    ",
    target: "M III Sept. 2021",
    bulan: "september",
    keterangan: "close",
    status: "close",
    divisi_id: 1,
  },

  {
    nama_program: "Always On Services",
    plan: "Maintenance Battery  Sentral EWSD,AT&T ,Transmisi dan BIR Battery/Ruangannya di Sto Gambir",
    target: "M III Sept. 2021",
    bulan: "september",
    keterangan: "close",
    status: "close",
    divisi_id: 1,
  },

  {
    nama_program: "Always On Services",
    plan: "Maintenance Rectifier Bening,Peco,Argus,Emerson,Fujitzu dan BIR Rectifier/Ruangannya di Sto Gambir",
    target: "M III Sept. 2021",
    bulan: "september",
    keterangan: "close",
    status: "close",
    divisi_id: 1,
  },

  {
    nama_program: "Always On Services",
    plan: "Maintenance /Pemanasan Genset Caterpillar kap.812 Kva Sto Cideng    ",
    target: "M IV Sept. 2021    ",
    bulan: "september",
    keterangan: "progres",
    status: "progres",
    divisi_id: 1,
  },

  {
    nama_program: "Always On Services",
    plan: "Maintenance Battery Sentral AT&T dan BIR Battery/Ruangannya di Sto Cideng  ",
    target: "M IV Sept. 2021",
    bulan: "september",
    keterangan: "progres",
    status: "progres",
    divisi_id: 1,
  },

  {
    nama_program: "Always On Services",
    plan: "Maintenance Rectifier Peco,Argus,Emerson dan BIR Rectifier/Ruangannya di Sto Cideng",
    target: "M IV Sept. 2021",
    bulan: "september",
    keterangan: "progres",
    status: "progres",
    divisi_id: 1,
  },

  {
    nama_program: "Always On Services",
    plan: "Maintenance Trafo Kap.630 Kva dan BIR Ruangannya di Sto Cideng",
    target: "M IV Sept. 2021",
    bulan: "september",
    keterangan: "progres",
    status: "progres",
    divisi_id: 1,
  },

  {
    nama_program: "Always On Services",
    plan: "Penambahan Air Aquades Batere VARTA Kap.3000 AH sebanyak 4 bank di Sto Cideng",
    target: "M IV Sept. 2021",
    bulan: "september",
    keterangan: "progres",
    status: "progres",
    divisi_id: 1,
  },

  {
    nama_program: "Always On Services",
    plan: "Maintenance /Pemanasan Genset Deutz kap.750 Kva Sto Kemayoran",
    target: "M V Sept. 2021",
    bulan: "september",
    keterangan: "progres",
    status: "progres",
    divisi_id: 1,
  },

  {
    nama_program: "Always On Services",
    plan: "Maintenance Rectifier Peco,Emerson dan BIR Rectifier/Ruangannya di Sto Kemayoran",
    target: "M V Sept. 2021",
    bulan: "september",
    keterangan: "progres",
    status: "progres",
    divisi_id: 1,
  },

  {
    nama_program: "Always On Services",
    plan: "Maintenance Battery  Sentral AT&T ,Transmisi dan BIR Battery/Ruangannya di Sto Kemayoran ",
    target: "M V Sept. 2021",
    bulan: "september",
    keterangan: "progres",
    status: "progres",
    divisi_id: 1,
  },

  {
    nama_program: "Always On Services",
    plan: "Penambahan Air Aquades Batere VARTA Kap.3000 AH sebanyak 2 bank di Sto Kemayoran",
    target: "M V Sept. 2021",
    bulan: "september",
    keterangan: "progres",
    status: "progres",
    divisi_id: 1,
  },

  // 2
  {
    nama_program: "Exellence Supplay Management",
    plan: "Pengawalan Tenoss",
    target: "continue",
    bulan: "september",
    keterangan: "progres",
    status: "progres",
    divisi_id: 2,
  },
  {
    nama_program: "Always On Services",
    plan: "Pengamanan OSP FO / Patroli",
    target: "continue",
    bulan: "september",
    keterangan: "progres",
    status: "progres",
    divisi_id: 2,
  },
  {
    nama_program: "Always On Services",
    plan: "Pengawalan Check List NewInfraCNR Transport",
    target: "continue",
    bulan: "september",
    keterangan: "progres",
    status: "progres",
    divisi_id: 2,
  },
  {
    nama_program: "Always On Services",
    plan: "Pengawalan Kabel dalam proyek MRT",
    target: "continue",
    bulan: "september",
    keterangan: "progres",
    status: "progres",
    divisi_id: 2,
  },
  {
    nama_program: "Always On Services",
    plan: "Migrasi Sentral CPTD To SM1B",
    target: "M I September",
    bulan: "september",
    keterangan: "close",
    status: "close",
    divisi_id: 2,
  },
  {
    nama_program: "Always On Services",
    plan: "Change Over SDH LUCENT GB1ADM1601 LS1 TO CPP UNITE",
    target: "M I September",
    bulan: "september",
    keterangan: "close",
    status: "close",
    divisi_id: 2,
  },
  {
    nama_program: "Always On Services",
    plan: "Change Over SDH LUCENT GB1ADM1602 LS1 TO CPP UNITE",
    target: "M I September",
    bulan: "september",
    keterangan: "close",
    status: "close",
    divisi_id: 2,
  },
  {
    nama_program: "Always On Services",
    plan: "Change Over SDH LUCENT GB1ADM1603 LS TO CPP UNITE",
    target: "M I September",
    bulan: "september",
    keterangan: "close",
    status: "close",
    divisi_id: 2,
  },
  {
    nama_program: "Always On Services",
    plan: "Change Over SDH LUCENT GB1ADM1604 LS1 TO CPP UNITE",
    target: "M I September",
    bulan: "september",
    keterangan: "close",
    status: "close",
    divisi_id: 2,
  },
  {
    nama_program: "Always On Services",
    plan: "Change Over SDH LUCENT GB1ADM1605 LS1 TO CPP UNITE",
    target: "M II September",
    bulan: "september",
    keterangan: "close",
    status: "close",
    divisi_id: 2,
  },
  {
    nama_program: "Always On Services",
    plan: "Change Over SDH LUCENT GB1ADM1606 LS1 TO CPP UNITE",
    target: "M II September",
    bulan: "september",
    keterangan: "close",
    status: "close",
    divisi_id: 2,
  },
  {
    nama_program: "Always On Services",
    plan: "Change Over SDH LUCENT GB1ADM1607 LS1 TO CPP UNITE",
    target: "M II September",
    bulan: "september",
    keterangan: "close",
    status: "close",
    divisi_id: 2,
  },
  {
    nama_program: "Always On Services",
    plan: "Change Over SDH LUCENT GB1ADM1608 LS1 TO CPP UNITE",
    target: "M II September",
    bulan: "september",
    keterangan: "close",
    status: "close",
    divisi_id: 2,
  },
  {
    nama_program: "Always On Services",
    plan: "Change Over SDH LUCENT GB1ADMU01 LS1 TO CPP UNITE",
    target: "M III September",
    bulan: "september",
    keterangan: "close",
    status: "close",
    divisi_id: 2,
  },
  {
    nama_program: "Always On Services",
    plan: "Change Over SDH LUCENT GB1ADMU02 LS1 TO CPP UNITE",
    target: "M III September",
    bulan: "september",
    keterangan: "close",
    status: "close",
    divisi_id: 2,
  },
  {
    nama_program: "Always On Services",
    plan: "Change Over SDH LUCENT GB1ADMU03 LS1 TO CPP UNITE",
    target: "M III September",
    bulan: "september",
    keterangan: "close",
    status: "close",
    divisi_id: 2,
  },
  {
    nama_program: "Always On Services",
    plan: "PENDATAAN FO RUANG MDF2 GAMBIR",
    target: "M III September",
    bulan: "september",
    keterangan: "close",
    status: "close",
    divisi_id: 2,
  },

  {
    nama_program: "Always On Services",
    plan: "VALIDASI DATA E1 GAMBIR",
    target: "M IV September",
    bulan: "september",
    keterangan: "close",
    status: "close",
    divisi_id: 2,
  },

  {
    nama_program: "Always On Services",
    plan: "VALIDASI DATA E1 CEMPAKA PUTIH ",
    target: "M IV September",
    bulan: "september",
    keterangan: "close",
    status: "close",
    divisi_id: 2,
  },

  {
    nama_program: "Always On Services",
    plan: "VALIDASI DATA E1 CIKINI",
    target: "M IV September",
    bulan: "september",
    keterangan: "close",
    status: "close",
    divisi_id: 2,
  },

  {
    nama_program: "Always On Services",
    plan: "VALIDASI DATA E1 KEMAYORAN",
    target: "M IV September",
    bulan: "september",
    keterangan: "close",
    status: "close",
    divisi_id: 2,
  },

  {
    nama_program: "Always On Services",
    plan: "VALIDASI DATA E1 CIDENG",
    target: "M IV September",
    bulan: "september",
    keterangan: "close",
    status: "close",
    divisi_id: 2,
  },

  // 3
  {
    nama_program: "Always On Services",
    plan: "Pengawalan Checklist via NewInfraCnr",
    target: "continue",
    bulan: "september",
    keterangan: "progres",
    status: "progres",
    divisi_id: 3,
  },
  {
    nama_program: "Excellence Supply Management",
    plan: "Support port ME utk layanan Datin",
    target: "continue",
    bulan: "september",
    keterangan: "progres",
    status: "progres",
    divisi_id: 3,
  },
  {
    nama_program: "Excellence Supply Management",
    plan: "Support OA Node B Via ME",
    target: "continue",
    bulan: "september",
    keterangan: "progres",
    status: "progres",
    divisi_id: 3,
  },
  {
    nama_program: "Excellence Supply Management",
    plan: "Support Integrasi ME To OLT Fiber Home STO GB, CKN, CPP, KMY",
    target: "continue",
    bulan: "september",
    keterangan: "progres",
    status: "progres",
    divisi_id: 3,
  },
  {
    nama_program: "Excellence Supply Management",
    plan: "Perapihan patchcore & labeling perangkat IP STO GB",
    target: "M I Sep",
    bulan: "september",
    keterangan: "close",
    status: "close",
    divisi_id: 3,
  },
  {
    nama_program: "Excellence Supply Management",
    plan: "Update Data potensi STO GB",
    target: "M I Sep",
    bulan: "september",
    keterangan: "close",
    status: "close",
    divisi_id: 3,
  },
  {
    nama_program: "Excellence Supply Management",
    plan: "Update Data potensi ME-HRB-JKT-PI",
    target: "M II Sep",
    bulan: "september",
    keterangan: "close",
    status: "close",
    divisi_id: 3,
  },
  {
    nama_program: "Excellence Supply Management",
    plan: "Update Data potensi ME2-HRB-JKT-PI",
    target: "M II Sep",
    bulan: "september",
    keterangan: "close",
    status: "close",
    divisi_id: 3,
  },
  {
    nama_program: "Excellence Supply Management",
    plan: "Update Data potensi ME-D2-HRB-GB-DKEU ",
    target: "M II Sep",
    bulan: "september",
    keterangan: "close",
    status: "close",
    divisi_id: 3,
  },
  {
    nama_program: "Excellence Supply Management",
    plan: "Update Data potensi ME2-D2-HRB-GB-DKEU    ",
    target: "M III Sep",
    bulan: "september",
    keterangan: "close",
    status: "close",
    divisi_id: 3,
  },
  {
    nama_program: "Excellence Supply Management",
    plan: "Update Topologi Network ME, SW, STO GB ",
    target: "M III Sep",
    bulan: "september",
    keterangan: "close",
    status: "close",
    divisi_id: 3,
  },
  {
    nama_program: "Excellence Supply Management",
    plan: "Update Topologi Network ME, SW, STO CKN",
    target: "M IV Sep",
    bulan: "september",
    keterangan: "close",
    status: "close",
    divisi_id: 3,
  },

  {
    nama_program: "Excellence Supply Management",
    plan: "Update Topologi Network ME, SW STO CPP ",
    target: "M IV Sep",
    bulan: "september",
    keterangan: "close",
    status: "close",
    divisi_id: 3,
  },
  {
    nama_program: "Excellence Supply Management",
    plan: "Update Topologi Network ME, SW STO CID",
    target: "M IV Sep",
    bulan: "september",
    keterangan: "close",
    status: "close",
    divisi_id: 3,
  },
  {
    nama_program: "Excellence Supply Management",
    plan: "Update Topologi Network ME, SW STO KMY",
    target: "M IV Sep",
    bulan: "september",
    keterangan: "close",
    status: "close",
    divisi_id: 3,
  },

  // 4
  {
    nama_program: "Excellence Supply Management",
    plan: "Monitoring Harian Pengisian New InfraCnR",
    target: "continue",
    bulan: "september",
    keterangan: "progres",
    status: "progres",
    divisi_id: 4,
  },
  {
    nama_program: "Excellence Supply Management",
    plan: "Penerbitan SIMARU (Surat Ijin Masuk Ruangan) Nodin",
    target: "continue",
    bulan: "september",
    keterangan: "progres",
    status: "progres",
    divisi_id: 4,
  },
  {
    nama_program: "Excellence Supply Management",
    plan: "Monitoring Pemakaian Ruang STO oleh Mitra",
    target: "continue",
    bulan: "september",
    keterangan: "progres",
    status: "progres",
    divisi_id: 4,
  },
  {
    nama_program: "Excellence Supply Management",
    plan: "Pengawalan Anggaran BODP SAP Nw Area Jkt Pusat",
    target: "continue",
    bulan: "september",
    keterangan: "progres",
    status: "progres",
    divisi_id: 4,
  },
  {
    nama_program: "Always On Services",
    plan: "Pembuatan Laporan Bulanan (OPI), Rekap Proker dan Jadwal Posko Infratrukstur 247",
    target: "M I Sept",
    bulan: "september",
    keterangan: "close",
    status: "close",
    divisi_id: 4,
  },
  {
    nama_program: "Always On Services",
    plan: "Pengawalan dan monitoring BODP Rutin Sentral, IPN Transport dan Cada",
    target: "M I Sept",
    bulan: "september",
    keterangan: "close",
    status: "close",
    divisi_id: 4,
  },
  {
    nama_program: "Always On Services",
    plan: "Pengawalan Distribusi Panjar BODP Rutin .IPN ,dan Trasport After Padiumkm",
    target: "M I Sept",
    bulan: "september",
    keterangan: "close",
    status: "close",
    divisi_id: 4,
  },
  {
    nama_program: "Always On Services",
    plan: "Pengawalan Penyerapan BODP Rutin Cada By padiumkm    ",
    target: "M II Sept",
    bulan: "september",
    keterangan: "close",
    status: "close",
    divisi_id: 4,
  },
  {
    nama_program: "Always On Services",
    plan: "Pengawalan Penyerapan BODP Rutin IPN By padiumkm",
    target: "M II Sept",
    bulan: "september",
    keterangan: "close",
    status: "close",
    divisi_id: 4,
  },
  {
    nama_program: "Always On Services",
    plan: "Pengawalan  Penyerapan BODP Rutin Transport By padiumkm",
    target: "M II Sept",
    bulan: "september",
    keterangan: "close",
    status: "close",
    divisi_id: 4,
  },
  {
    nama_program: "Always On Services",
    plan: "Pembuatan Laporan ICCA",
    target: "M II Sept",
    bulan: "september",
    keterangan: "close",
    status: "close",
    divisi_id: 4,
  },
  {
    nama_program: "Always On Services",
    plan: "Pengawalan penyerapan  anggaran Catu Daya ( RRA)",
    target: "M III Sept",
    bulan: "september",
    keterangan: "close",
    status: "close",
    divisi_id: 4,
  },
  {
    nama_program: "Always On Services",
    plan: "Pengawalan Siswa PKL",
    target: "M III Sept",
    bulan: "september",
    keterangan: "close",
    status: "close",
    divisi_id: 4,
  },
  {
    nama_program: "Always On Services",
    plan: "Pembuatan Laporan tutup buku Cash opname",
    target: "M III Sept",
    bulan: "september",
    keterangan: "close",
    status: "close",
    divisi_id: 4,
  },
  {
    nama_program: "Always On Services",
    plan: "Pengawalan BIR STO CPP dan CKN",
    target: "M III Sept",
    bulan: "september",
    keterangan: "close",
    status: "close",
    divisi_id: 4,
  },
  {
    nama_program: "Always On Services",
    plan: "Pengawalan BIR STO CID KMY dan GBR",
    target: "M III Sept",
    bulan: "september",
    keterangan: "close",
    status: "close",
    divisi_id: 4,
  },

  // 5
  {
    nama_program: "Excellence Supply Management",
    plan: "Monitoring & Perbaikan gangguan by http://helpdesk.telkom.co.id",
    target: "continue",
    bulan: "september",
    keterangan: "progres",
    status: "progres",
    divisi_id: 5,
  },
  {
    nama_program: "Excellence Supply Management",
    plan: "Validasi data Sarker Seat Managemen by http://cnemas.telkom.co.id",
    target: "continue",
    bulan: "september",
    keterangan: "progres",
    status: "progres",
    divisi_id: 5,
  },
  {
    nama_program: "Excellence Supply Management",
    plan: "Monitoring NMS Link LAN JakPUS by http://Zabbix.10.55.1.50",
    target: "continue",
    bulan: "september",
    keterangan: "progres",
    status: "progres",
    divisi_id: 5,
  },
  {
    nama_program: "Always On Service",
    plan: "Monitoring Validasi data Laptop Non Kar",
    target: "M II Sept",
    bulan: "september",
    keterangan: "progres",
    status: "progres",
    divisi_id: 5,
  },
  {
    nama_program: "Always On Service",
    plan: "Monitoring pengantian Modem Aruba 2540 Switch 48 Pots dari RNO (5 Swicth untuk Sto Gbr Ok)",
    target: "M III Sept",
    bulan: "september",
    keterangan: "progres",
    status: "progres",
    divisi_id: 5,
  },
  {
    nama_program: "Always On Service",
    plan: "Monitoring validasi seat managemen VI Non Cash",
    target: "M IIII Sept",
    bulan: "september",
    keterangan: "progres",
    status: "progres",
    divisi_id: 5,
  },
  {
    nama_program: "Always On Service",
    plan: "Monitoring Validasi Laporan CNeMas [96,37 %]",
    target: "M I Okto",
    bulan: "oktober",
    keterangan: "progres",
    status: "progres",
    divisi_id: 5,
  },
  {
    nama_program: "Always On Service",
    plan: "Validasi Laporan Devloyment [96,44 %]",
    target: "M I Okto",
    bulan: "oktober",
    keterangan: "progres",
    status: "progres",
    divisi_id: 5,
  },
  {
    nama_program: "Always On Service",
    plan: "Validasi Laporan Dismantling [96,53 %]",
    target: "M I Okto",
    bulan: "oktober",
    keterangan: "progres",
    status: "progres",
    divisi_id: 5,
  },
  {
    nama_program: "Always On Service",
    plan: "Validasi Laporan IBM [91,03 %]",
    target: "M I Okto",
    bulan: "oktober",
    keterangan: "progres",
    status: "progres",
    divisi_id: 5,
  },
  {
    nama_program: "Always On Service",
    plan: "Aktivasi Link Switch untuk kebutuhan LAN Divisi SDA Sto GB LT.6",
    target: "M I Okto",
    bulan: "oktober",
    keterangan: "close",
    status: "close",
    divisi_id: 5,
  },
  {
    nama_program: "Always On Service",
    plan: "Aktivasi Link Switch untuk kebutuhan LAN Divisi SDA Kebon Sirih 37.",
    target: "M I Okto",
    bulan: "oktober",
    keterangan: "close",
    status: "close",
    divisi_id: 5,
  },
  {
    nama_program: "Always On Service",
    plan: "Suport Pengawalan Acara Vaksinasi covid 19 Witel JakPus",
    target: "M I Okto",
    bulan: "oktober",
    keterangan: "close",
    status: "close",
    divisi_id: 5,
  },
  {
    nama_program: "Always On Service",
    plan: "CO Link Switch RNO Percetakan Negara By Gambir To Metro Cikini.",
    target: "M IV Okto",
    bulan: "oktober",
    keterangan: "progres",
    status: "progres",
    divisi_id: 5,
  },
];

const proker_seeder = async () => {
  try {
    const result = await Proker.bulkCreate(proker_dummy);
    return result;
  } catch (error) {
    return error;
  }
};

module.exports = proker_seeder;
